name: Deploy Laravel to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /var/www/laravel
          pwd
          # ${{ secrets.APP_DIR }}
          # echo "Pulling latest changes"
          # git pull origin main
          # echo "Installing dependencies"
          # composer install --no-dev --optimize-autoloader
          # echo "Running migrations"
          # php artisan migrate --force
          # echo "Caching config and routes"
          # php artisan config:cache
          # php artisan route:cache
          # echo "Restarting web server"
          # sudo systemctl restart nginx
        EOF
